# setting routes

# locale internal rest api route
spygar_setting_rest_internal_locale:
    path: rest/internal/{page}/locale/{limit}
    defaults: { _controller: spygar.locale.rest.internal.controller::list }

spygar_setting_rest_internal_active_locale:
    path: rest/internal/{page}/active-locale/{limit}
    defaults: { _controller: spygar.locale.rest.internal.controller::activeList }
 
# currency internal rest api route
spygar_setting_rest_internal_currency:
    path: rest/internal/{page}/currency/{limit}
    defaults: { _controller: spygar.currency.rest.internal.controller::list }

# attribute Group route
spygar_setting_rest_internal_attribute_group:
    path: rest/internal/{page}/attribute-group/{limit}
    defaults: { _controller: spygar.attribute_group.rest.internal.controller::list }

spygar_setting_rest_internal_attribute_group_detail:
    path: rest/internal/{code}/attribute-group
    defaults: { _controller: spygar.attribute_group.rest.internal.controller::detail }

spygar_setting_rest_internal_attribute_group_create_or_update:
    path: rest/internal/attribute-group/create
    defaults: { _controller: spygar.attribute_group.rest.internal.controller::createOrUpdate }

spygar_setting_rest_internal_attribute_group_add_attributes:
    path: rest/internal/attribute-group/add-attributes
    defaults: { _controller: spygar.attribute_group.rest.internal.controller::addAttributesIntoAttributeGroup }

spygar_setting_rest_internal_attribute_group_remove_attributes:
    path: rest/internal/attribute-group/remove-attribute
    defaults: { _controller: spygar.attribute_group.rest.internal.controller::removeAttributesIntoAttributeGroup }

spygar_setting_rest_internal_attribute_group_delete:
    path: rest/internal/attribute-group/delete
    defaults: { _controller: spygar.attribute_group.rest.internal.controller::delete }

# attribute route
spygar_setting_rest_internal_attribute_create_form:
    path: rest/internal/create/attribute
    defaults: { _controller: spygar.attribute.rest.internal.controller::attributeCreateForm }

spygar_setting_rest_internal_attribute_list:
    path: /rest/internal/{page}/attribute/{limit}
    defaults: { _controller: spygar.attribute.rest.internal.controller::list }

spygar_setting_rest_internal_get_attribute:
    path: /rest/internal/{code}/attribute
    defaults: { _controller: spygar.attribute.rest.internal.controller::getAttribute }

spygar_setting_rest_internal_attribute_create:
    path: /rest/internal/attribute/create
    defaults: { _controller: spygar.attribute.rest.internal.controller::createAttribute }

spygar_setting_rest_internal_attributes_by_types:
    path: /rest/internal/attribute-by/types
    defaults: { _controller: spygar.attribute.rest.internal.controller::attributesByTypes }

# attribute options routes
spygar_setting_rest_internal_attribute_option_create_or_update:
    path: /rest/internal/attribute-option/create
    defaults: { _controller: spygar.attribute_option.rest.internal.controller::createOption }

spygar_setting_rest_internal_attribute_option_delete:
    path: /rest/internal/attribute-option/delete
    defaults: { _controller: spygar.attribute_option.rest.internal.controller::removeOption }

# family routes

spygar_setting_rest_internal_family_form:
    path: /rest/internal/{code}/form/family
    defaults: { _controller: spygar.family.rest.internal.controller::generateForm }

spygar_setting_rest_internal_family_list:
    path: /rest/internal/{page}/family/{limit}
    defaults: { _controller: spygar.family.rest.internal.controller::list }

spygar_setting_rest_internal_family_create:
    path: /rest/internal/family/create
    defaults: { _controller: spygar.family.rest.internal.controller::create }

spygar_setting_rest_internal_family_delete:
    path: /rest/internal/family/delete
    defaults: { _controller: spygar.family.rest.internal.controller::delete }

spygar_setting_rest_internal_family_details:
    path: /rest/internal/{code}/family
    defaults: { _controller: spygar.family.rest.internal.controller::details }

spygar_setting_rest_internal_family_add_attributes:
    path: /rest/internal/family/add-attributes
    defaults: { _controller: spygar.family.rest.internal.controller::addAttributes }

# category routes
spygar_setting_rest_internal_category_list:
    path: /rest/internal/category/list
    defaults: { _controller: spygar.category.rest.internal.controller::list }

spygar_setting_rest_internal_category_create:
    path: /rest/internal/category/create
    defaults: { _controller: spygar.category.rest.internal.controller::create }

spygar_setting_rest_internal_category_update:
    path: /rest/internal/category/update
    defaults: { _controller: spygar.category.rest.internal.controller::update }
    

# associations
spygar_setting_rest_internal_association_list:
    path: /rest/internal/{page}/association/{limit}
    defaults: { _controller: spygar.association_type.rest.internal.controller::list }

spygar_setting_rest_internal_association_create_or_update:
    path: /rest/internal/association/create
    defaults: { _controller: spygar.association_type.rest.internal.controller::createOrUpdate }

spygar_setting_rest_internal_association_details:
    path: /rest/internal/{id}/association
    defaults: { _controller: spygar.association_type.rest.internal.controller::details }
# system configuration routes
spygar_system_configuration_details:
    path: /rest/internal/system/configuration
    defaults: { _controller: spygar.system_configuration.rest.internal.controller::details }

spygar_system_configuration_create_update:
    path: /rest/internal/system/configuration/create
    defaults: { _controller: spygar.system_configuration.rest.internal.controller::createAndUpdate }
