services:
    _defaults:
        autowire: true  
        autoconfigure: true
        public: true

    # spygar.fixture.installer.command:
    #     public: true
    #     class: Spygar\Platform\Bundle\InstallerBundle\Commands\FixtureInstallerCommand
    #     arguments:
    #         - "@doctrine.orm.entity_manager"
    #         - "@spygar.repository.provider"
    #     tags:
    #         - { name: console.command }