datagrid:
    user-grid:
        options:
            method: GET
            url: /api/users
        columns:
            name:
                label: Name
                data_name:     Name        
            roles:
                label:         Roles
                data_name:     label
            last_login:
                label:         Last Login
                data_name:     last_login
            active:
                label:         Active
                frontend_type: enabled            
            created:
                label:         Created
        actions:
            edit:
                iconName: editIcon
                method: POST
                url: /api/user/{id}/edit
            delete:
                iconName: deleteIcon
                method: POST
                url: /api/user/{id}/delete
            toggle_status:
                iconName: deleteIcon
                method: POST
                url: /api/user/{id}/toggle
        # mass_actions:
        #     delete:
        #         label: user_datagrid.mass_action_group.bulk_actions.label
        #         method: POST
        #         url: /api/mass-delete
        # sorters:
        #     columns:
        #         identifier:
        #             data_name: identifier
        #             sorter: product_field
        #         family:
        #             data_name: familyLabel
        #             sorter:    product_family
        #         enabled:
        #             data_name: enabled
        #             sorter:    product_field
        #         completeness:
        #             data_name: ratio
        #             sorter:    product_completeness
        #         created:
        #             data_name: created
        #             sorter:    product_field
        #         updated:
        #             data_name: updated
        #             sorter:    product_field
        # filters:
        #     columns:
        #         name:
        #             type: string
        #             label: 'user_datagrid.filters.label_or_identifier.label_with_uuid'
        #             data_name: label_or_identifier
        #         enabled:
        #             type:      boolean
        #             label:     'user_datagrid.filters.enabled.label'
        #             data_name: enabled
        #             options:
        #                 field_options:
        #                     choices:
        #                         Enabled: 1
        #                         Disabled: 0
        #         created:
        #             type:      product_date
        #             ftype:     date
        #             data_name: created
        #             label:     'user_datagrid.filters.created.label'
        #         email:
        #             type: product_value_string
        #             ftype: identifier
        #             label: 'user_datagrid.filters.identifier.label'
        #             data_name: identifier
        #             options:
        #                 field_options:
        #                     attr:
        #                         choice_list: true
        #                         empty_choice: true