services:
    _defaults:
        autowire: true  
        autoconfigure: true
        public: true
        
    # Locale internal controller api
    spygar.locale.rest.internal.controller:
        class: Spygar\Platform\Bundle\SettingBundle\Controller\Rest\Internal\LocaleController
        public: true
        arguments:
            - "@spygar.locale.repository"

    # Currency internal currency  controller api
    spygar.currency.rest.internal.controller:
        class: Spygar\Platform\Bundle\SettingBundle\Controller\Rest\Internal\CurrencyController
        public: true
        arguments:
            - "@spygar.currency.repository"

    # Attribute Group internal controller api
    spygar.attribute_group.rest.internal.controller:
        class: Spygar\Platform\Bundle\SettingBundle\Controller\Rest\Internal\AttributeGroupController
        public: true
        arguments:
            - "@spygar.attribute_group.repository"
            - "@spygar.attribute.repository"
    
    # Attribute internal controller api
    spygar.attribute.rest.internal.controller:
        class: Spygar\Platform\Bundle\SettingBundle\Controller\Rest\Internal\AttributeController
        public: true
        arguments:
            - "@spygar.attribute.repository"
            - "@spygar.attribute.form"
            - "@spygar.attribute.factory"

    # Attribute option internal controller api
    spygar.attribute_option.rest.internal.controller:
        class: Spygar\Platform\Bundle\SettingBundle\Controller\Rest\Internal\AttributeOptionController
        public: true
        arguments:
            - "@spygar.attribute_option.repository"
            - "@spygar.attribute_option.factory"

    # Family internal controller api
    spygar.family.rest.internal.controller:
        class: Spygar\Platform\Bundle\SettingBundle\Controller\Rest\Internal\FamilyController
        public: true
        arguments:
            - "@spygar.family.repository"
            - "@spygar.family.factory"
            - "@spygar.family.form"

    # category controller
    spygar.category.rest.internal.controller:
        class: Spygar\Platform\Bundle\SettingBundle\Controller\Rest\Internal\CategoryController
        public: true
        arguments:
            - "@spygar.category.repository"
            - "@spygar.locale.repository"

    # association type controller
    spygar.association_type.rest.internal.controller:
        class: Spygar\Platform\Bundle\SettingBundle\Controller\Rest\Internal\AssociationTypeController
        public: true
        arguments:
            - "@spygar.association_type.repository"

    # system configuration controller
    spygar.system_configuration.rest.internal.controller:
        class: Spygar\Platform\Bundle\SettingBundle\Controller\Rest\Internal\ConfigurationController
        public: true
        arguments:
            - "@spygar.system.configuration.repository"