services:
    _defaults:
        autowire: true  
        autoconfigure: true
        public: true
    
    spygar.attribute.factory:
        class: Spygar\Platform\Bundle\SettingBundle\Factory\AttributeFactory
        public: true
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@spygar.attribute.repository"
            - "@spygar.attribute_group.repository"

    spygar.family.factory:
        class: Spygar\Platform\Bundle\SettingBundle\Factory\FamilyFactory
        public: true
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@spygar.attribute.repository"

    spygar.attribute_option.factory:
        class: Spygar\Platform\Bundle\SettingBundle\Factory\AttributeOptionFactory
        public: true
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@spygar.attribute.repository"
            - "@spygar.attribute_option.repository"