services:   
    _defaults:
        autowire: true  
        autoconfigure: true
        public: true
    
    spygar.attribute.form:
        class: Spygar\Platform\Bundle\SettingBundle\Form\AttributeForm
        public: true
        arguments:
            - "@spygar.attribute_group.repository"
            - "@spygar.locale.repository"

    spygar.family.form:
        class: Spygar\Platform\Bundle\SettingBundle\Form\FamilyForm
        public: true
        arguments:
            - "@spygar.attribute.repository"
            - "@spygar.locale.repository"