services:
    _defaults:
        autowire: true  
        autoconfigure: true
        public: true
    
    spygar.attribute.repository:
        class: Spygar\Platform\Bundle\SettingBundle\Repository\AttributeRepository
        public: true
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@spygar.attribute_option.repository"
            - "@spygar.attribute_group.repository"

    spygar.attribute_option.repository:
        class: Spygar\Platform\Bundle\SettingBundle\Repository\AttributeOptionRepository
        public: true
        arguments:
            - "@doctrine.orm.entity_manager"

    spygar.attribute_group.repository:
        class: Spygar\Platform\Bundle\SettingBundle\Repository\AttributeGroupRepository
        public: true
        arguments:
            - "@doctrine.orm.entity_manager"

    spygar.locale.repository:
        class: Spygar\Platform\Bundle\SettingBundle\Repository\LocaleRepository
        public: true
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@spygar.system.configuration.repository"
            
    spygar.currency.repository:
        class: Spygar\Platform\Bundle\SettingBundle\Repository\CurrencyRepository
        public: true
        arguments:
            - "@doctrine.orm.entity_manager"

    spygar.family.repository:
        class: Spygar\Platform\Bundle\SettingBundle\Repository\FamilyRepository
        public: true
        arguments:
            - "@doctrine.orm.entity_manager"

    spygar.category.repository:
        class: Spygar\Platform\Bundle\SettingBundle\Repository\CategoryRepository
        public: true
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@spygar.usermanagement.user.context"

    spygar.association_type.repository:
        class: Spygar\Platform\Bundle\SettingBundle\Repository\AssociationTypeRepository
        public: true
        arguments:
            - "@doctrine.orm.entity_manager"

    spygar.system.configuration.repository:
        class: Spygar\Platform\Bundle\SettingBundle\Repository\ConfigurationRepository
        public: true
        arguments:
            - "@doctrine.orm.entity_manager"

