
services:
    _defaults:
        public: true
        autoconfigure: true
        autowire: true
        
    spygar.usermanagement.user.repository:
        class: Spygar\UserManagement\Bundle\Repository\UserRepository
        # factory: ['@doctrine.orm.default_entity_manager', getRepository]
        arguments:
            - "@doctrine"
    spygar.usermanagement.role.repository:
        class: Spygar\UserManagement\Bundle\Repository\RoleRepository
        arguments:
            - "@doctrine"