services:
    _defaults:
        public: true
        autoconfigure: true
        autowire: true
        
    spygar_user_provider:
        class: Spygar\UserManagement\Component\Provider\UserProvider
        arguments:
            - "@spygar.usermanagement.user.repository"