services:
    _defaults:
        autowire: true  
        autoconfigure: true
        public: true

    spygar.product.repository:
        public: true
        class: Spygar\Platform\Bundle\ProductBundle\Repository\ProductRepository
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@spygar.family.repository"